name: Kkyuni Acttions
on:
  pull_request:
    branches: 
      - develop
    types: [opened, synchronize, reopened, edited, ready_for_review, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bukld with Gradle
        run: ./gradlew build
